engines:
  csslint:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR2"
  fixme:
    enabled: false
  phpmd:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - php
ratings:
  paths:
  - Classes/**/*
  - Configuration/**/*
exclude_paths:
- Tests/**/*
